# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
dependencies:
  - compilers 
  - scikit-learn 
  - numpy 
  - c-compiler 
  - cxx-compiler 
  - cython 
  - matplotlib 
  - jax 
  - flax 
  - jaxlib 
  - matplotlib 
  - seaborn 
  - tqdm
  - pip
  - pip:
    - git+https://github.com/sissa-data-science/DADApy@v0.3.2
    
