# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
  - numba

dependencies:
  - python>=3.9
  - numpy<1.24,>=1.18
  - scipy>=1.10.0
  - numba==0.56.4
  - pip
